language: c
cache:
  ccache: true
  directories:
    - $HOME/.ccache
compiler:
  - gcc
branches:
  except:
    - /^.*doc-.*$/
env:
  matrix:
    - BITCOINVERSION=v0.11.2
sudo: false
addons:
  apt:
    sources:
    - boost-latest
    packages:
    # Bitcoin Core dependencies
    - build-essential
    - libtool
    - autotools-dev
    - automake
    - pkg-config
    - libssl-dev
    - libevent-dev
    - bsdmainutils
    - libboost1.55-all-dev
    - libdb-dev
    - libdb++-dev
    # libbitcoinrpc dependencies
    - libcurl4-openssl-dev
    - libjansson-dev
    - uuid-dev
before_install:
  - dpkg -s libcurl4-openssl-dev libjansson-dev uuid-dev
before_script:
  # Disable cache size limit
  - ccache -F 0 && ccache -M 2G
  - ccache -s
  - git clone https://github.com/bitcoin/bitcoin.git
  - cd bitcoin
  - git checkout ${BITCOINVERSION}
  - ./autogen.sh
  - ./configure --without-gui --with-incompatible-bdb
  - make
  - ccache -s
  - cd ..
script:
  - make
  - make test
