language: c
compiler:
  - gcc
branches:
  except:
    - /^.*doc-.*$/
install:
  - sudo add-apt-repository -y ppa:bitcoin/bitcoin
  - sudo apt-get update -qq
  - sudo apt-get install bitcoind
  - sudo apt-get install -qq libcurl4-openssl-dev libjansson-dev uuid-dev
  - dpkg -s libcurl4-openssl-dev libjansson-dev uuid-dev
script:
  - make
  - sudo make install
  - make test
  - sudo make uninstall
